### ISSUE TITLE
Exception in display_interface.py

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/minipupper_ros#1]
`rosrun display_interface display_interface.py` results in an exception:
```sh
 $ rosrun display_interface display_interface.py 
Traceback (most recent call last):
  File "/home/ubuntu/mnpp_ws/src/minipupper_ros/display_interface/scripts/display_interface.py", line 6, in <module>
    from cv_bridge import CvBridge, CvBridgeError
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/__init__.py", line 6, in <module>
    from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
SystemError: initialization of cv_bridge_boost raised unreported exception
```
I found the following answer on "ROS answers": [cv_bridge_boost raised unreported exception when importing cv_bridge](https://answers.ros.org/question/362388/cv_bridge_boost-raised-unreported-exception-when-importing-cv_bridge/).

The fix is to import cv2 before cv_bridge:

```python3
import cv2
from cv_bridge import CvBridge, CvBridgeError
```

**Comment by mangdangroboticsclub** [comment]
Hi Joep, 
Many thanks for your feedback, we confirmed your advice, you are right.
Could you please post a pull request directly?
I will merge your pull request?
Thanks!
