### ISSUE TITLE
in ROS install for PC, wstool command not found

### ISSUE THREAD

**Issue by lamachine** [mangdangroboticsclub/minipupper_ros#11]
I am following the minipupper ros instructions.  I did the installs then moved into carto.  The next command uses wstool, and I got bash: wstool: Command not found.  With a bit of digging around I found a solution by use pip install -force-reinstall -U wstool and it works now.  RPI4.

**Comment by lamachine** [comment]
This solution does NOT work for rosdep.  Same problem.

sudo apt-get install python-rosdep   

It will install Python3-Rosdep2.  the init command then asks you to run rosdep update.  This apparently completes the init command.

**Comment by mangdangroboticsclub** [comment]
Please try the auto-install cartographer command below, thanks!
$sudo apt-get install ros-noetic-cartographer-ros
