### ISSUE TITLE
yaml.load missing one requirement 'Loader', ROS instructions

### ISSUE THREAD

**Issue by lamachine** [mangdangroboticsclub/minipupper_ros#12]
Apparently I have a midas touch in reverse.  At the wstool merge step, I get the above error.  Searching a bit provided me with this clue

> Now, the load() function requires parameter loader=Loader.
> 
> If your YAML file contains just simple YAML (str, int, lists), try to use yaml.safe_load() instead of yaml.load(). And If you need FullLoader, you can use yaml.full_load().

pip freeze shows my version of pyYAML as 6.0 and this is apparently an issue after 5.4.  

pip install --upgrade piyaml == 5.4 resolved it.

**Comment by mangdangroboticsclub** [comment]
You already fixed it, thanks!
You can install cartographer automatically with the command below now, thanks!
$sudo apt-get install ros-noetic-cartographer-ros
