### ISSUE TITLE
ROS 1.1.1 install issues, follow-on

### ISSUE THREAD

**Issue by lamachine** [mangdangroboticsclub/minipupper_ros#13]
Let me start with the fact I am new to ROS.  See the first two issues for other problems with the same sections.

rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
        WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
        ERROR: the following packages/stacks could not have their rosdep keys resolved
        to system dependencies:
        cartographer_ros_msgs: Cannot locate rosdep definition for [std_msgs]
        cartographer_rviz: Cannot locate rosdep definition for [rviz]
        cartographer_ros: Cannot locate rosdep definition for [visualization_msgs]

src/cartographer/scripts/install_abseil.sh
        Appears to have worked
sudo apt-get remove ros-${ROS_DISTRO}-abseil-cpp
        Skipped based on rosdep install above
catkin_make_isolated --install --use-ninja
        bash: catkin_make_isolated: command not found
source install_isolated/setup.bash
        Gave up at this point and wrote up this issue

**Comment by mangdangroboticsclub** [comment]
You can install cartographer automatically with the command below now, thanks!
$sudo apt-get install ros-noetic-cartographer-ros
