### ISSUE TITLE
issue in cartographer configuration

### ISSUE THREAD

**Issue by ali4neo** [mangdangroboticsclub/minipupper_ros#16]
i am not able to configure my controll pc with cartographer and ROS Neotic
using ubuntu 20.04.

here are the error from installing ros neotic 

~/carto_ws$ rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y

WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
cartographer: [libabsl-dev] defined as "not available" for OS version [focal]
cartographer_rviz: Cannot locate rosdep definition for [rviz]
cartographer_ros_msgs: Cannot locate rosdep definition for [std_msgs]
cartographer_ros: Cannot locate rosdep definition for [visualization_msgs]

also adding the final build output as a screenshot below.
![Screenshot from 2022-08-27 12-41-58](https://user-images.githubusercontent.com/57340531/187019593-5607fc74-ef46-4276-b2d2-4078d8a1bbd2.png)

**Comment by sskorol** [comment]
Check this issue for details: https://github.com/cartographer-project/cartographer_ros/issues/1726

**Comment by Tiryoh** [comment]
I found a way to work around the problem.
https://github.com/cartographer-project/cartographer_ros/pull/1745

I guess the following commands works.

```
cd ~/carto_ws
source /opt/ros/noetic/setup.bash
sed -i -e "s%<depend>libabsl-dev</depend>%<\!--<depend>libabsl-dev</depend>-->%g" src/cartographer/package.xml
rosdep install --from-paths src --ignore-src -r -y 
```

**Comment by mangdangroboticsclub** [comment]
You can also install cartographer automatically with the command below now, thanks!
$sudo apt-get install ros-noetic-cartographer-ros
