### ISSUE TITLE
Where is the " .minipupper.repos " file as mention in the README.md

### ISSUE THREAD

**Issue by Skammi** [mangdangroboticsclub/minipupper_ros#20]
The README.md mention in step " 1.1.2 Mini Pupper ROS packages installation " to execute :
vcs import < minipupper_ros/.minipupper.repos --recursive

The file: " .minipupper.repos ' does not exit.

**Comment by sskorol** [comment]
It's in the repo [root](https://github.com/mangdangroboticsclub/minipupper_ros/blob/ros1/.minipupper.repos). However, it was pushed only 21 hrs ago. So if you cloned the repo earlier, pull the changes first, and then try again.

**Comment by Skammi** [comment]
Thanks resolved

Jacob

**Comment by Skammi** [comment]
Resolved after repo update
