### ISSUE TITLE
where is display_interface.py 

### ISSUE THREAD

**Issue by Skammi** [mangdangroboticsclub/minipupper_ros#23]
In minipupperdocs.readthedocs.io under 2.2.2. LCD Screen a simple interface is mentioned:
rosrun display_interface display_interface.py

Where is this package?

**Comment by 0nhc** [comment]
Hey, it's here:
https://github.com/mangdangroboticsclub/mini_pupper_ros/blob/ros1/mini_pupper_control/scripts/display_interface.py

**Comment by Skammi** [comment]
Found it. Documentation is not up to date. On "https://minipupperdocs.readthedocs.io/en/latest/guide/SLAM.html#quick-start" under 2.2.2 state: rosrun display_interface display_interface.py
should be: rosrun mini_pupper_control display_interface.py
