### ISSUE TITLE
Integrate sskorol's web controller into mangdang workspace

### ISSUE THREAD

**Issue by sskorol** [mangdangroboticsclub/minipupper_ros#26]
Integrate [minipupper-teleop](https://github.com/sskorol/minipupper-teleop) into `ros1` branch for further assessment.

**Comment by mangdangroboticsclub** [comment]
Sorry for the late feedback.
You did a lot of work and the code is awesome.
However, if we merge this, there will be a lot of unnecessary code for users who want to simply use the ROS package, and the usability as a teaching material will be not good.
Furthermore, it seems that you are trying to do something different, such as reading the servo's initial angle from the xml file, not from EEPROM.
So I will not merge your PR, please maintain it by yourself, many thanks for your awesome work.
