### ISSUE TITLE
display_interface.py script needs to be executable

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/minipupper_ros#3]
The `display_interface.py` script in the `display_interface` package must be executable.
Otherwise `rosrun` or `roslaunch` will not find it.

**Comment by mangdangroboticsclub** [comment]
Hi Joep, 
Many thanks for your feedback, we confirmed your advice, you are right.
Could you please post a pull request directly?
I will merge your pull request?
Thanks!
