### ISSUE TITLE
display_interface package has wrong dependencies

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/minipupper_ros#4]
It claims to depend on `roscpp`, `rospy`, `std_msgs`. But actually it needs `rospy`, `sensor_msgs`, `cv_bridge`.

**Comment by mangdangroboticsclub** [comment]
Hi Joep, 
Many thanks for your feedback, we confirmed your advice, you are right.
Could you please post a pull request directly?
I will merge your pull request?
Thanks!

**Comment by mangdangroboticsclub** [comment]
already merged your pull, many thanks!
