### ISSUE TITLE
Update for ROS 2 Humble (Patch Release 2)

### ISSUE THREAD

**Issue by Tiryoh** [mangdangroboticsclub/minipupper_ros#47]
Plan: https://github.com/mangdangroboticsclub/mini_pupper_ros/blob/ros2/HUMBLE_PLAN.md

## ROS packages

- [ ] Cleanup urdf and xacro

## Documentation

- [ ] Add a detailed tutorial to try teleop with simulated Mini Pupper 
- [ ] Add a detailed tutorial to try slam with simulated Mini Pupper 
- [ ] Add a detailed tutorial to try navigation with simulated Mini Pupper
- [ ] Add a detailed tutorial to try teleop with real Mini Pupper
- [ ] Add a detailed tutorial to try slam with real Mini Pupper
- [ ] Add a detailed tutorial to try navigation with real Mini Pupper

**Comment by mangdangroboticsclub** [comment]
already fixed, many thanks!
