### ISSUE TITLE
Colcon build error in humble

### ISSUE THREAD

**Issue by ChangerC77** [mangdangroboticsclub/minipupper_ros#76]
After type this command: `colcon build --symlink-install`
it occurs some errors below:
![5nTkFwqIsj](https://github.com/mangdangroboticsclub/mini_pupper_ros/assets/44107275/fd8dd684-524a-4287-9c4a-91c6d02e8f83)

**Comment by Ericsii** [comment]
Please make sure if you installed `champ` properly.
You can follow the link below.
https://github.com/chvmp/champ
