### ISSUE TITLE
Issue with Minipupper ROS1 - Spawning Multiple Instances in Gazebo

### ISSUE THREAD

**Issue by adamzr2000** [mangdangroboticsclub/minipupper_ros#80]
Hello ROS community,

I am currently working with Minipupper in ROS1 and I'm facing an issue while trying to spawn two instances of it in Gazebo. To achieve this, I am using a parameter in the gazebo.launch file called "robot_name," which makes use of namespaces for each robot instance. Here's how I start the launch file:

"roslaunch mini_pupper_gazebo gazebo.launch robot_name:=robot1"

I've observed that in the minipupper_bringup/champ_bringup.launch file, two ekf_localization nodes are launched(base_to_footprint_ekf and footprint_to_odom_ekf). When I comment out these lines everything works, but when it's not commented, things don't work and the following error appears:

"Could not obtain transform from base_link to robot1/base_footprint. Error was "base_link" passed to lookupTransform argument source_frame does not exist."

I've checked the tf_tree, and it seems to be configured correctly with the appropriate node and tf_prefix namespaces.

If anyone has encountered a similar issue or has insights into why the ekf_localization nodes might be causing this problem, I would greatly appreciate your help.

[logs.txt](https://github.com/mangdangroboticsclub/mini_pupper_ros/files/13190258/logs.txt)

![rqtgraph](https://github.com/mangdangroboticsclub/mini_pupper_ros/assets/103327212/5023aac5-eee6-49e8-bbdb-4af60589f5f0)

![tftree](https://github.com/mangdangroboticsclub/mini_pupper_ros/assets/103327212/10bb9192-b2a0-458a-9d2b-626c9844bd87)

**Comment by mangdangroboticsclub** [comment]
We only maintain ros2 now.
